### ISSUE TITLE
Error when trying to go to the plugin configuration page

### ISSUE THREAD

**Issue by brlumen** [mantisbt-plugins/CheckPlugin#1]
Hi! 
The plugin does not work if the mantisbt configuration is set:

```
$g_display_errors = array(
    E_ALL               => DISPLAY_ERROR_HALT,
);

$g_show_detailed_errors = ON;

$g_stop_on_errors = ON;
```

![image](https://user-images.githubusercontent.com/26021974/231711638-53e236a2-e653-4432-bf7f-57f3ccbeaa84.png)
![image](https://user-images.githubusercontent.com/26021974/231711075-ce87e794-e837-47d7-b884-c22cf0a8c1bd.png)

**Comment by ghost** [comment]
That makes sense, a warning is triggered because the config option is not yet there in the table. This will happen upon finishing the config. Best is to use E_ERROR.
However I will see if I can fix this.

**Comment by ghost** [comment]
Issue fixed, found a small type being the root cause of it all.
